### ISSUE TITLE
SSH Config Hardening

### ISSUE THREAD

**Issue by austenadler** [norpol/opensshd-tor-easy-setup#8]
Consider adding these options:

- `UseDNS no`: Does nothing but may leak information in the query
- `Protocol 2`: Do not allow less secure protocol 1 clients

**Comment by norpol** [comment]
Hey, thank you for reviewing the config and reporting potential issues! 2019 was quite some intense time for me :D.

According to recent `man sshd_config`

> `UseDNS`
> [...] If this option is set to no (the default) [...]

And as far as I see `Protocol 1` is also disabled for recent OpenSSH servers, though man-page doesn't mention that.

Will close it therefor.
